import { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app " />
        <link rel="public" href="favicon.ico" />
      </Head>

      <main>
        <h1>
          Welcome to <a href="https://nextjs.org">Next.js</a>
        </h1>
        <p>
          Lorem ipsum dolor sit, amet consectetur adipisicing elit. Cumque nemo,
          eligendi a amet nobis alias vel illum repellendus molestiae earum!
          Corporis repellat dolorem nulla distinctio commodi vel impedit
          nesciunt doloribus.
        </p>
      </main>
    </>
  );
};

export default Home;
